import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import MainMenu from "@/components/layouts/MainMenu";
import "bootstrap/dist/css/bootstrap.min.css";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";

const siliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-siliguri",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={siliguri.variable}>
      <body>
        <Header />
        <MainMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
